{
    "customProperties":{
        "formComponent":false,
        "layout":{
            "responsive":true
        }
    },
    "encapsulation":108,
    "items":[
        {
            "customProperties":{
                "attributes":{
                    "class":"row"
                },
                "properties":{
                    "packagename":"12grid",
                    "specname":"row"
                }
            },
            "items":[
                {
                    "customProperties":{
                        "attributes":{
                            "class":"col-md-12"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"column"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"center-container"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"centercontainer"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"center-container-content"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"div"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"page-title",
                                                "text":"Dashboard"
                                            },
                                            "location":"1,1",
                                            "name":"label_1",
                                            "styleClass":"page-title",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"56423C7C-0364-4469-8225-8677D49045FC"
                                        }
                                    ],
                                    "location":"1,1",
                                    "typeid":46,
                                    "uuid":"4E5B3E36-65A1-4BFD-B116-FCCBC7E42B02"
                                }
                            ],
                            "location":"0,0",
                            "typeid":46,
                            "uuid":"113C0266-8B91-4184-86C3-7AA22343E3C3"
                        }
                    ],
                    "location":"0,0",
                    "typeid":46,
                    "uuid":"BCD0FDBB-EAAF-49F4-8829-9D3827B9F000"
                }
            ],
            "location":"2,2",
            "typeid":46,
            "uuid":"0493A06B-D43A-4D50-AFA1-79F42ADC9882"
        },
        {
            "customProperties":{
                "attributes":{
                    "class":"row"
                },
                "properties":{
                    "packagename":"12grid",
                    "specname":"row"
                }
            },
            "items":[
                {
                    "customProperties":{
                        "attributes":{
                            "class":"col-md-6 padding-left-30"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"column"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"row"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"row"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"col-md-12 padding-left-30"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"column"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "styleClass":"section-title",
                                                "text":"Games Played Per Month"
                                            },
                                            "location":"1,1",
                                            "name":"label",
                                            "styleClass":"section-title",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"A2AADB2F-459B-46FE-BBFA-E61AD77023C4"
                                        }
                                    ],
                                    "location":"0,0",
                                    "typeid":46,
                                    "uuid":"32818922-64A4-46B4-8191-A23004D6EDE5"
                                }
                            ],
                            "location":"0,0",
                            "typeid":46,
                            "uuid":"484187A2-ED0A-4205-ADF1-B3480FB3B8E8"
                        },
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"row"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"row"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"col-md-12"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"column"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "foundset":{
                                                    "dataproviders":{
                                                        "label":"label",
                                                        "value":"total_games"
                                                    },
                                                    "foundsetSelector":"db:/chess_club_db/vw_games_per_month",
                                                    "loadAllRecords":true
                                                },
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "type":"line"
                                            },
                                            "location":"1,1",
                                            "name":"chart",
                                            "typeName":"svychartjs-chart",
                                            "typeid":47,
                                            "uuid":"E81A47F3-75B8-4AEB-90E2-6568C69DA936"
                                        }
                                    ],
                                    "location":"0,0",
                                    "typeid":46,
                                    "uuid":"4EE5EB2D-02AC-4126-A4E5-997BF35469FA"
                                }
                            ],
                            "location":"0,0",
                            "typeid":46,
                            "uuid":"E68981F5-3DD4-47E8-9A06-4C0611E7BF6E"
                        }
                    ],
                    "location":"0,0",
                    "typeid":46,
                    "uuid":"CDF6A9C2-F426-4B8D-B7BE-17D5F818FC96"
                },
                {
                    "customProperties":{
                        "attributes":{
                            "class":"col-md-6"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"column"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"row"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"row"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"col-md-12"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"column"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "foundset":{
                                                    "dataproviders":{
                                                        "label":"label",
                                                        "value":"total"
                                                    },
                                                    "foundsetSelector":"db:/chess_club_db/vw_membership_distribution",
                                                    "loadAllRecords":"true"
                                                },
                                                "location":{
                                                    "x":1,
                                                    "y":1
                                                },
                                                "type":"doughnut"
                                            },
                                            "location":"1,1",
                                            "name":"chart_copy666",
                                            "typeName":"svychartjs-chart",
                                            "typeid":47,
                                            "uuid":"E692D5FA-55B7-4844-92E1-E813A4FBE5FE"
                                        }
                                    ],
                                    "location":"0,0",
                                    "typeid":46,
                                    "uuid":"07318D31-F8AD-46D7-8698-07CE32ADBC7C"
                                }
                            ],
                            "location":"3,3",
                            "typeid":46,
                            "uuid":"31D720C5-06DE-4367-999C-B03C8BD4337D"
                        },
                        {
                            "json":{
                                "location":{
                                    "x":2,
                                    "y":2
                                },
                                "styleClass":"section-title",
                                "text":"Membership Type Distribution"
                            },
                            "location":"2,2",
                            "name":"label_copy962",
                            "styleClass":"section-title",
                            "typeName":"bootstrapcomponents-label",
                            "typeid":47,
                            "uuid":"6A59A5AF-9876-4D8F-B66A-7526ADA3ABD4"
                        }
                    ],
                    "location":"40,50",
                    "typeid":46,
                    "uuid":"D280EBC3-6B58-4257-83E4-B63029A393BD"
                }
            ],
            "location":"4,4",
            "typeid":46,
            "uuid":"305EEC05-FBC8-4F69-B7B2-740D5E28980B"
        },
        {
            "customProperties":{
                "attributes":{
                    "class":"row"
                },
                "properties":{
                    "packagename":"12grid",
                    "specname":"row"
                }
            },
            "items":[
                {
                    "customProperties":{
                        "attributes":{
                            "class":"col-md-12"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"column"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"row"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"row"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"col-md-12"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"column"
                                        }
                                    },
                                    "items":[
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"row"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"row"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"col-md-12"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"column"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "customProperties":{
                                                                "attributes":{
                                                                    "class":"row"
                                                                },
                                                                "properties":{
                                                                    "packagename":"12grid",
                                                                    "specname":"row"
                                                                }
                                                            },
                                                            "items":[
                                                                {
                                                                    "customProperties":{
                                                                        "attributes":{
                                                                            "class":"col-md-12"
                                                                        },
                                                                        "properties":{
                                                                            "packagename":"12grid",
                                                                            "specname":"column"
                                                                        }
                                                                    },
                                                                    "items":[
                                                                        {
                                                                            "cssPosition":"0,-1,-1,0,100%,100%",
                                                                            "json":{
                                                                                "brandLogo":"0CE439B8-9FBD-4812-8B31-8E391DAD5502",
                                                                                "brandLogoStyleClass":"navLogo",
                                                                                "cssPosition":{
                                                                                    "bottom":"-1",
                                                                                    "height":"100%",
                                                                                    "left":"0",
                                                                                    "right":"-1",
                                                                                    "top":"0",
                                                                                    "width":"100%"
                                                                                },
                                                                                "location":{
                                                                                    "x":40,
                                                                                    "y":50
                                                                                },
                                                                                "menuItems":[
                                                                                    {
                                                                                        "displayType":"BUTTON",
                                                                                        "onAction":"EE10A894-36A3-4ACB-8904-485D83C176B1",
                                                                                        "svyUUID":"FDAB8CFD-B791-425A-9C9A-E4E2B25CDAE9",
                                                                                        "text":"Dashboard"
                                                                                    },
                                                                                    {
                                                                                        "displayType":"BUTTON",
                                                                                        "onAction":"0279FDC8-A7E7-4EB0-9F66-92250786696F",
                                                                                        "svyUUID":"783B1DEF-5FAA-4466-A44A-CD8BEDCF4D5A",
                                                                                        "text":"Manage Members"
                                                                                    },
                                                                                    {
                                                                                        "displayType":"BUTTON",
                                                                                        "onAction":"A065CEDE-5E90-450E-8474-17245D739D70",
                                                                                        "svyUUID":"F91B9746-7239-410E-B99F-BD7180FB8CF3",
                                                                                        "text":"Tournaments"
                                                                                    },
                                                                                    {
                                                                                        "displayType":"BUTTON",
                                                                                        "isActive":true,
                                                                                        "onAction":"91DA7FBB-1816-4603-910B-645AACD7B95A",
                                                                                        "svyUUID":"1DE9D9BC-2BCA-4CA2-B402-082ECE467493",
                                                                                        "text":"Standings"
                                                                                    }
                                                                                ]
                                                                            },
                                                                            "location":"40,50",
                                                                            "name":"navbar_11",
                                                                            "typeName":"bootstrapextracomponents-navbar",
                                                                            "typeid":47,
                                                                            "uuid":"76EFC155-4D91-4CF3-8FA4-1A053F089491"
                                                                        }
                                                                    ],
                                                                    "location":"0,0",
                                                                    "typeid":46,
                                                                    "uuid":"12C80605-A020-4777-ACA8-5BCB15542EA8"
                                                                }
                                                            ],
                                                            "location":"40,50",
                                                            "typeid":46,
                                                            "uuid":"1D64C12A-6AB1-4960-8BC2-41FA9CD55FDE"
                                                        }
                                                    ],
                                                    "location":"0,0",
                                                    "typeid":46,
                                                    "uuid":"12531172-0643-4FF4-8AD3-6C8CDF58AC1F"
                                                }
                                            ],
                                            "location":"40,50",
                                            "typeid":46,
                                            "uuid":"77B9C532-05B7-4A67-886A-7CAAEF541D64"
                                        }
                                    ],
                                    "location":"0,0",
                                    "typeid":46,
                                    "uuid":"9E24F135-4D0D-4CDE-858B-D540523D889F"
                                }
                            ],
                            "location":"40,50",
                            "typeid":46,
                            "uuid":"95D41338-44F8-4107-B380-E9C63B9ED210"
                        }
                    ],
                    "location":"0,0",
                    "typeid":46,
                    "uuid":"C9C520FE-8BDE-4842-BC02-2557BBC3E9CA"
                }
            ],
            "location":"1,1",
            "typeid":46,
            "uuid":"3327EA33-ACCB-44A7-8083-FF3FDBD561F7"
        },
        {
            "customProperties":{
                "attributes":{
                    "class":"row"
                },
                "properties":{
                    "packagename":"12grid",
                    "specname":"row"
                }
            },
            "items":[
                {
                    "customProperties":{
                        "attributes":{
                            "class":"col-md-4 padding-left-30 padding-right-20"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"column"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"svy-csspositioncontainer"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"csspositioncontainer"
                                }
                            },
                            "items":[
                                {
                                    "cssPosition":"106,-1,-1,182,188,77",
                                    "json":{
                                        "cssPosition":{
                                            "bottom":"-1",
                                            "height":"77",
                                            "left":"182",
                                            "right":"-1",
                                            "top":"106",
                                            "width":"188"
                                        },
                                        "dataProviderID":"averageRating",
                                        "location":{
                                            "x":78,
                                            "y":120
                                        },
                                        "styleClass":"stat-value"
                                    },
                                    "location":"78,120",
                                    "name":"datalabel_13",
                                    "styleClass":"stat-value",
                                    "typeName":"bootstrapcomponents-datalabel",
                                    "typeid":47,
                                    "uuid":"5729435C-BA44-46D4-A414-A1A84BADCAD5"
                                },
                                {
                                    "cssPosition":"53,-1,-1,156,200,51",
                                    "json":{
                                        "cssPosition":{
                                            "bottom":"-1",
                                            "height":"51",
                                            "left":"156",
                                            "right":"-1",
                                            "top":"53",
                                            "width":"200"
                                        },
                                        "location":{
                                            "x":78,
                                            "y":62
                                        },
                                        "styleClass":"stat-label",
                                        "text":"Average Rating"
                                    },
                                    "location":"78,62",
                                    "name":"label_12",
                                    "styleClass":"stat-label",
                                    "typeName":"bootstrapcomponents-label",
                                    "typeid":47,
                                    "uuid":"5F935C3D-5B6B-49C2-A8DE-4B44098273E9"
                                },
                                {
                                    "cssPosition":"41,-1,-1,29,80%,60%",
                                    "json":{
                                        "cssPosition":{
                                            "bottom":"-1",
                                            "height":"60%",
                                            "left":"29",
                                            "right":"-1",
                                            "top":"41",
                                            "width":"80%"
                                        },
                                        "location":{
                                            "x":57,
                                            "y":80
                                        },
                                        "styleClass":"stat-card warning"
                                    },
                                    "location":"57,80",
                                    "name":"label_7_copy447",
                                    "styleClass":"stat-card warning",
                                    "typeName":"bootstrapcomponents-label",
                                    "typeid":47,
                                    "uuid":"7C1FE7CB-9471-42DF-B756-4D274E866C9F"
                                }
                            ],
                            "location":"40,50",
                            "size":"200,200",
                            "typeid":46,
                            "uuid":"0677880F-A19A-4FBF-8EC4-1B21DD266040"
                        }
                    ],
                    "location":"0,0",
                    "typeid":46,
                    "uuid":"44C5B0EC-532C-4FCB-8B83-47E0B144C0DE"
                },
                {
                    "customProperties":{
                        "attributes":{
                            "class":"col-md-4 padding-left-30 padding-right-20"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"column"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"svy-csspositioncontainer"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"csspositioncontainer"
                                }
                            },
                            "items":[
                                {
                                    "cssPosition":"57,-1,-1,138,121,30",
                                    "json":{
                                        "cssPosition":{
                                            "bottom":"-1",
                                            "height":"30",
                                            "left":"138",
                                            "right":"-1",
                                            "top":"57",
                                            "width":"121"
                                        },
                                        "location":{
                                            "x":73,
                                            "y":56
                                        },
                                        "styleClass":"stat-label",
                                        "text":"Total Players"
                                    },
                                    "location":"73,56",
                                    "name":"label_9",
                                    "styleClass":"stat-label",
                                    "typeName":"bootstrapcomponents-label",
                                    "typeid":47,
                                    "uuid":"A635779A-85F2-43CE-A28A-FE7D9B7D85C8"
                                },
                                {
                                    "cssPosition":"40,-1,-1,9,80%,60%",
                                    "json":{
                                        "cssPosition":{
                                            "bottom":"-1",
                                            "height":"60%",
                                            "left":"9",
                                            "right":"-1",
                                            "top":"40",
                                            "width":"80%"
                                        },
                                        "location":{
                                            "x":57,
                                            "y":80
                                        },
                                        "styleClass":"stat-card info"
                                    },
                                    "location":"57,80",
                                    "name":"label_7",
                                    "styleClass":"stat-card info",
                                    "typeName":"bootstrapcomponents-label",
                                    "typeid":47,
                                    "uuid":"AD69B8E0-9A4F-45EF-8445-07544733B5BA"
                                },
                                {
                                    "cssPosition":"107,-1,-1,167,148,42",
                                    "json":{
                                        "cssPosition":{
                                            "bottom":"-1",
                                            "height":"42",
                                            "left":"167",
                                            "right":"-1",
                                            "top":"107",
                                            "width":"148"
                                        },
                                        "dataProviderID":"totalMembers",
                                        "location":{
                                            "x":63,
                                            "y":125
                                        },
                                        "styleClass":"stat-value"
                                    },
                                    "location":"63,125",
                                    "name":"datalabel_8",
                                    "styleClass":"stat-value",
                                    "typeName":"bootstrapcomponents-datalabel",
                                    "typeid":47,
                                    "uuid":"ED0E0DF6-3DC3-42EB-B9DB-CD546734DB64"
                                }
                            ],
                            "location":"0,0",
                            "size":"200,200",
                            "typeid":46,
                            "uuid":"13793EFE-9471-4EA1-8201-8AF491EC0733"
                        }
                    ],
                    "location":"0,0",
                    "typeid":46,
                    "uuid":"5957D1AE-80E8-4DAF-BF2B-2BF5B97BF444"
                },
                {
                    "customProperties":{
                        "attributes":{
                            "class":"col-md-4 padding-left-30 padding-right-20"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"column"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"svy-csspositioncontainer"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"csspositioncontainer"
                                }
                            },
                            "items":[
                                {
                                    "cssPosition":"39,-1,-1,29,80%,60%",
                                    "json":{
                                        "cssPosition":{
                                            "bottom":"-1",
                                            "height":"60%",
                                            "left":"29",
                                            "right":"-1",
                                            "top":"39",
                                            "width":"80%"
                                        },
                                        "location":{
                                            "x":70,
                                            "y":88
                                        },
                                        "styleClass":"stat-card success"
                                    },
                                    "location":"70,88",
                                    "name":"label_14",
                                    "styleClass":"stat-card success",
                                    "typeName":"bootstrapcomponents-label",
                                    "typeid":47,
                                    "uuid":"1E8EED02-A4A1-4732-A87A-9DDB8C06BF03"
                                },
                                {
                                    "cssPosition":"96,-1,-1,192,159,54",
                                    "json":{
                                        "cssPosition":{
                                            "bottom":"-1",
                                            "height":"54",
                                            "left":"192",
                                            "right":"-1",
                                            "top":"96",
                                            "width":"159"
                                        },
                                        "dataProviderID":"activeMembers",
                                        "location":{
                                            "x":110,
                                            "y":134
                                        },
                                        "styleClass":"stat-value"
                                    },
                                    "location":"110,134",
                                    "name":"datalabel_16",
                                    "styleClass":"stat-value",
                                    "typeName":"bootstrapcomponents-datalabel",
                                    "typeid":47,
                                    "uuid":"87B2F93A-363E-483D-9C77-10D228EDAEA8"
                                },
                                {
                                    "cssPosition":"54,-1,-1,157,156,30",
                                    "json":{
                                        "cssPosition":{
                                            "bottom":"-1",
                                            "height":"30",
                                            "left":"157",
                                            "right":"-1",
                                            "top":"54",
                                            "width":"156"
                                        },
                                        "location":{
                                            "x":77,
                                            "y":76
                                        },
                                        "styleClass":"stat-label",
                                        "text":"Active Players"
                                    },
                                    "location":"77,76",
                                    "name":"label_15",
                                    "styleClass":"stat-label",
                                    "typeName":"bootstrapcomponents-label",
                                    "typeid":47,
                                    "uuid":"ABE4F946-A976-468A-BB89-6875E20B68BA"
                                }
                            ],
                            "location":"40,50",
                            "size":"200,200",
                            "typeid":46,
                            "uuid":"726A5F23-F5FF-402D-B591-9C4F76500F13"
                        }
                    ],
                    "location":"0,0",
                    "typeid":46,
                    "uuid":"5F2BE3A2-7A0C-43B9-81DC-F58A9084502E"
                }
            ],
            "location":"3,3",
            "typeid":46,
            "uuid":"36BF0DD5-4B04-4A75-BFBD-DAAC136C1C08"
        },
        {
            "customProperties":{
                "attributes":{
                    "class":"row"
                },
                "properties":{
                    "packagename":"12grid",
                    "specname":"row"
                }
            },
            "items":[
                {
                    "customProperties":{
                        "attributes":{
                            "class":"col-md-12 padding-top-30"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"column"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"row"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"row"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"col-md-12"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"column"
                                        }
                                    },
                                    "items":[
                                        {
                                            "customProperties":{
                                                "attributes":{
                                                    "class":"center-container"
                                                },
                                                "properties":{
                                                    "packagename":"12grid",
                                                    "specname":"centercontainer"
                                                }
                                            },
                                            "items":[
                                                {
                                                    "customProperties":{
                                                        "attributes":{
                                                            "class":"center-container-content"
                                                        },
                                                        "properties":{
                                                            "packagename":"12grid",
                                                            "specname":"div"
                                                        }
                                                    },
                                                    "items":[
                                                        {
                                                            "json":{
                                                                "location":{
                                                                    "x":40,
                                                                    "y":50
                                                                },
                                                                "styleClass":"section-title",
                                                                "text":"Active vs Inactive Members"
                                                            },
                                                            "location":"40,50",
                                                            "name":"label_copy962_copy464_copy135",
                                                            "styleClass":"section-title",
                                                            "typeName":"bootstrapcomponents-label",
                                                            "typeid":47,
                                                            "uuid":"3B1BFFD2-2904-4B24-837D-3EBDF90AB410"
                                                        }
                                                    ],
                                                    "location":"1,1",
                                                    "typeid":46,
                                                    "uuid":"0F9CA51D-3AF4-4F99-99C7-1B428F696227"
                                                }
                                            ],
                                            "location":"0,0",
                                            "typeid":46,
                                            "uuid":"C62D27FB-4A6D-42F3-94A1-EEA7C9212BB7"
                                        }
                                    ],
                                    "location":"0,0",
                                    "typeid":46,
                                    "uuid":"F20B828D-CEB3-4275-95FE-6CFCD7254464"
                                }
                            ],
                            "location":"0,0",
                            "typeid":46,
                            "uuid":"83540A5E-5523-4F6B-A2DF-EF4007824B60"
                        },
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"row"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"row"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"col-md-12"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"column"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "foundset":{
                                                    "dataproviders":{
                                                        "label":"label",
                                                        "value":"total"
                                                    },
                                                    "foundsetSelector":"db:/chess_club_db/vw_active_members_distribution",
                                                    "loadAllRecords":"true"
                                                },
                                                "location":{
                                                    "x":40,
                                                    "y":50
                                                }
                                            },
                                            "location":"40,50",
                                            "name":"chart_4_copy33",
                                            "typeName":"svychartjs-chart",
                                            "typeid":47,
                                            "uuid":"C9E520FA-B9E5-447D-8C9D-7F22C58A0BF2"
                                        }
                                    ],
                                    "location":"0,0",
                                    "typeid":46,
                                    "uuid":"C0BE9FD2-C9D4-4869-8737-5F0D7C6B81B2"
                                }
                            ],
                            "location":"0,0",
                            "typeid":46,
                            "uuid":"CC2F9734-6BAB-46C7-8C80-A2344E824504"
                        }
                    ],
                    "location":"0,0",
                    "typeid":46,
                    "uuid":"E0A25FF1-7585-4C1C-A809-A2D628D1BD40"
                }
            ],
            "location":"6,6",
            "typeid":46,
            "uuid":"9EED1D1A-16A6-4E63-932A-DA56B8585DE7"
        },
        {
            "customProperties":{
                "attributes":{
                    "class":"row"
                },
                "properties":{
                    "packagename":"12grid",
                    "specname":"row"
                }
            },
            "items":[
                {
                    "customProperties":{
                        "attributes":{
                            "class":"col-md-6 padding-left-30"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"column"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"row"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"row"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"col-md-12"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"column"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "location":{
                                                    "x":40,
                                                    "y":50
                                                },
                                                "styleClass":"section-title",
                                                "text":"Upcoming Tournaments per Status"
                                            },
                                            "location":"40,50",
                                            "name":"label_copy962_copy464_copy185",
                                            "styleClass":"section-title",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"EAAE6350-D8B4-4F8B-B834-D3DEBFAE9F8E"
                                        }
                                    ],
                                    "location":"0,0",
                                    "typeid":46,
                                    "uuid":"E9BD70AC-95CB-40C3-9397-0F35333F6831"
                                }
                            ],
                            "location":"0,0",
                            "typeid":46,
                            "uuid":"14318EA7-7C07-4ECD-9378-7867019CB6BC"
                        },
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"row"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"row"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"col-md-12"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"column"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "foundset":{
                                                    "dataproviders":{
                                                        "label":"label",
                                                        "value":"total"
                                                    },
                                                    "foundsetSelector":"db:/chess_club_db/vw_tournament_status_distribution",
                                                    "loadAllRecords":"true"
                                                },
                                                "location":{
                                                    "x":40,
                                                    "y":50
                                                },
                                                "type":"bar"
                                            },
                                            "location":"40,50",
                                            "name":"chart_2_copy894",
                                            "typeName":"svychartjs-chart",
                                            "typeid":47,
                                            "uuid":"DB1E1C9C-017B-4E0B-87BB-8A1C524E2D37"
                                        }
                                    ],
                                    "location":"0,0",
                                    "typeid":46,
                                    "uuid":"9548C836-5FE2-48D5-AE58-E97AACB9FF97"
                                }
                            ],
                            "location":"0,0",
                            "typeid":46,
                            "uuid":"E280FA3C-4C90-4A9B-ACBC-F995572749E9"
                        }
                    ],
                    "location":"0,0",
                    "typeid":46,
                    "uuid":"B97D5738-9B4E-40D2-8AF3-DCCB63F61814"
                },
                {
                    "customProperties":{
                        "attributes":{
                            "class":"col-md-6"
                        },
                        "properties":{
                            "packagename":"12grid",
                            "specname":"column"
                        }
                    },
                    "items":[
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"row"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"row"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"col-md-12"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"column"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "location":{
                                                    "x":40,
                                                    "y":50
                                                },
                                                "styleClass":"section-title",
                                                "text":"Games Results"
                                            },
                                            "location":"40,50",
                                            "name":"label_copy962_copy464",
                                            "styleClass":"section-title",
                                            "typeName":"bootstrapcomponents-label",
                                            "typeid":47,
                                            "uuid":"B450A023-A223-4F8E-AF17-FFDD3F406740"
                                        }
                                    ],
                                    "location":"0,0",
                                    "typeid":46,
                                    "uuid":"2A25B482-55A7-45FA-A0E9-AFCD6B484640"
                                }
                            ],
                            "location":"0,0",
                            "typeid":46,
                            "uuid":"A1FAEF8E-5746-4208-8AFF-4F8BDB604F78"
                        },
                        {
                            "customProperties":{
                                "attributes":{
                                    "class":"row"
                                },
                                "properties":{
                                    "packagename":"12grid",
                                    "specname":"row"
                                }
                            },
                            "items":[
                                {
                                    "customProperties":{
                                        "attributes":{
                                            "class":"col-md-12"
                                        },
                                        "properties":{
                                            "packagename":"12grid",
                                            "specname":"column"
                                        }
                                    },
                                    "items":[
                                        {
                                            "json":{
                                                "foundset":{
                                                    "dataproviders":{
                                                        "label":"label",
                                                        "value":"total"
                                                    },
                                                    "foundsetSelector":"db:/chess_club_db/vw_game_results_distribution",
                                                    "loadAllRecords":"true"
                                                },
                                                "location":{
                                                    "x":40,
                                                    "y":50
                                                },
                                                "type":"doughnut"
                                            },
                                            "location":"40,50",
                                            "name":"chart_3_copy459",
                                            "typeName":"svychartjs-chart",
                                            "typeid":47,
                                            "uuid":"697AD21C-DE39-4F62-9DA7-F3E882E19E35"
                                        }
                                    ],
                                    "location":"0,0",
                                    "typeid":46,
                                    "uuid":"8EC48404-CC6D-4047-9290-FE188A190B44"
                                }
                            ],
                            "location":"0,0",
                            "typeid":46,
                            "uuid":"E0B7F8B9-31B5-409A-BBBE-7AC2208F9F73"
                        }
                    ],
                    "location":"0,0",
                    "typeid":46,
                    "uuid":"D2C9DA3A-A00D-44B0-AF6F-0E05DA993FD4"
                }
            ],
            "location":"5,5",
            "typeid":46,
            "uuid":"A45B64F4-CE73-49C5-AF3F-813D808899A9"
        }
    ],
    "name":"dashboard",
    "navigatorID":"-1",
    "onShowMethodID":"6AE9E284-469B-44AD-BA6B-0741E37A7C74",
    "showInMenu":true,
    "typeid":3,
    "uuid":"C89E260A-04E4-4D2A-9C60-3792EF87B068"
}